# Generated by Django 5.1 on 2024-09-16 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='field',
            new_name='name',
        ),
    ]
