# Generated by Django 5.1 on 2024-09-20 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_app', '0003_remove_image_product_image_content_type_and_more'),
        ('store_app', '0015_category_remove_clothes_product_category_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='category',
        ),
    ]
