# Generated by Django 5.1 on 2024-09-15 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banner',
            old_name='field',
            new_name='title',
        ),
        migrations.CreateModel(
            name='image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='banners/')),
                ('banner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store_app.banner')),
            ],
        ),
    ]
