# Generated by Django 5.1 on 2024-09-15 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0002_rename_field_banner_title_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='url',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
