# Generated by Django 5.1 on 2024-09-16 01:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_app', '0001_initial'),
        ('store_app', '0004_alter_image_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='digital_product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='digital_categories', to='social_app.category'),
        ),
        migrations.CreateModel(
            name='clothes_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chothes_categories', to='social_app.category')),
            ],
        ),
    ]
