# Generated by Django 5.1 on 2024-09-16 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0006_clothes_product_brand_clothes_product_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothes_product',
            name='image',
            field=models.ImageField(null=True, upload_to='banner_image'),
        ),
    ]
