# Generated by Django 5.1 on 2024-09-16 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0008_alter_clothes_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clothes_product',
            name='image',
        ),
    ]
