# Generated by Django 5.1 on 2024-09-16 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('store_app', '0009_remove_clothes_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='store_app_images', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='image',
            name='object_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
