# Generated by Django 5.1 on 2024-09-19 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0010_image_content_type_image_object_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='banner',
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(null=True, upload_to='banner_imageclothes_products'),
        ),
    ]
