# Generated by Django 5.1 on 2024-09-19 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0011_remove_image_banner_alter_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(null=True, upload_to='banner_image , clothes_images'),
        ),
    ]
