# Generated by Django 5.1 on 2024-09-20 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0015_category_remove_clothes_product_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='field',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='color',
            old_name='field',
            new_name='color',
        ),
    ]
