# Generated by Django 5.1 on 2024-10-11 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0021_description_specificationdetail_remove_color_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='description',
            name='description_detail',
        ),
        migrations.RemoveField(
            model_name='image',
            name='url',
        ),
        migrations.DeleteModel(
            name='DetailDescription',
        ),
    ]
