# Generated by Django 5.1 on 2024-10-13 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0023_clothes_product_ia_sale_clothes_product_sale_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothes_product',
            name='sale_price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='digital_product',
            name='sale_price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=20),
        ),
    ]
